CREATE TABLE IF NOT EXISTS `Users` (
	`user_id` INT NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(50) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Lists` (
	`list_id` INT NOT NULL AUTO_INCREMENT,
	`list_name` VARCHAR(255) NOT NULL,
	`user_id` INT NOT NULL,
	PRIMARY KEY (`list_id`),
	FOREIGN KEY (`user_id`) REFERENCES Users(`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Items` (
	`item_id` INT NOT NULL AUTO_INCREMENT,
	`task` VARCHAR(255) NOT NULL,
	`list_id` INT NOT NULL,
	`completed` BOOLEAN NOT NULL,
	PRIMARY KEY (`item_id`),
	FOREIGN KEY (`list_id`) REFERENCES Lists(`list_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;